name: demo
on: push
jobs:
  gobenchdata-checks:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with: { fetch-depth: 1 }
    - name: gobenchdata checks
      uses: ./
      with:
        GO_TEST_FLAGS: -cpu 1,2
        CHECKS: true
        CHECKS_CONFIG: ./demo/gobenchdata-checks.yml
        # TODO: update after release
        PUBLISH_REPO: bobheadxi/gobenchdata-v1-demo
        PUBLISH_BRANCH: master
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

  gobenchdata-publish:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with: { fetch-depth: 1 }
    - name: gobenchdata publish
      uses: ./
      with:
        PRUNE_COUNT: 30
        GO_TEST_FLAGS: -cpu 1,2
        PUBLISH: true
        # TODO: update after release
        PUBLISH_REPO: bobheadxi/gobenchdata-v1-demo
        PUBLISH_BRANCH: master
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
