name: publish@v1
on:
  release:
    types: [ published ]

jobs:
  publish_v1:
    if: github.event_name == 'release' && contains(github.ref, 'v1')
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: set up credentials
      run: |
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global user.name "${GITHUB_ACTOR}"
        git remote set-url origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/bobheadxi/gobenchdata.git
    - name: update tag
      run: |
        git tag -fa v1 -m "Update v1 tag"
        git push origin v1 --force
